language: node_js
node_js:
  - 15
before_install:
  - cd backend
  - npm install
  - cd frontend
  - npm install
  - npm run coverage
  - npm run build
# install:
#   - npm install
# script:
#   - npm run coverage
#   - npm run build
